# Generated by Django 4.2.7 on 2025-11-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('memory_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('active_transactions', models.IntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('fraud_detected', models.IntegerField(default=0)),
                ('avg_response_time', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(db_index=True)),
                ('merchant', models.CharField(max_length=200)),
                ('card_number', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='US', max_length=2)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('fraud_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('is_fraud', models.BooleanField(db_index=True, default=False)),
                ('fraud_reasons', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['transaction_id'], name='api_transac_transac_83000d_idx'), models.Index(fields=['date'], name='api_transac_date_26e12b_idx'), models.Index(fields=['status'], name='api_transac_status_0f4e6a_idx'), models.Index(fields=['is_fraud'], name='api_transac_is_frau_37ff5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action'], name='api_auditlo_action_0a1743_idx'), models.Index(fields=['transaction_id'], name='api_auditlo_transac_486c55_idx'), models.Index(fields=['timestamp'], name='api_auditlo_timesta_da87a7_idx')],
            },
        ),
    ]
