# Generated by Django 4.2.7 on 2025-12-01
# Migration to add risk_score and reason_code fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),  # Adjust this to your last migration
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='risk_score',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Rule-based risk score (0-100)',
                max_digits=5,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reason_code',
            field=models.TextField(
                blank=True,
                help_text='Detailed fraud detection reasons',
                null=True
            ),
        ),
    ]
