# Generated by Django 4.2.7 on 2025-12-08 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_user_refreshtoken_oauthaccount"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="api_auditlo_action_0a1743_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="api_auditlo_transac_486c55_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="api_auditlo_timesta_da87a7_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="api_transac_transac_83000d_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="api_transac_date_26e12b_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="api_transac_status_0f4e6a_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="api_transac_is_frau_37ff5c_idx",
        ),
        # First, add user_string field to store old string values
        migrations.AddField(
            model_name="auditlog",
            name="user_string",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        # Add user field to transaction
        migrations.AddField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="api.user",
            ),
        ),
        # Data migration: Copy old user string to user_string, then clear user field
        migrations.RunPython(
            code=lambda apps, schema_editor: None,  # Skip - we'll handle manually
            reverse_code=migrations.RunPython.noop,
        ),
        # Remove the old user field (CharField) before adding the new one (ForeignKey)
        migrations.RemoveField(
            model_name="auditlog",
            name="user",
        ),
        # Add the new user field as ForeignKey
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="api.user",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={("user", "transaction_id")},
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user", "action"], name="api_auditlo_user_id_c3bd49_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user", "transaction_id"], name="api_auditlo_user_id_3a94a3_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user", "timestamp"], name="api_auditlo_user_id_8f69e8_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["user", "transaction_id"], name="api_transac_user_id_21e962_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["user", "date"], name="api_transac_user_id_aacb53_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["user", "status"], name="api_transac_user_id_daa5cc_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["user", "is_fraud"], name="api_transac_user_id_42fe14_idx"),
        ),
    ]
