# Generated by Django 4.2.7 on 2025-12-08 02:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_auditlog_api_auditlo_action_0a1743_idx_and_more"),
    ]

    operations = []
